name: Crée une image du frontend qui fonctionne avec un backend en local

on: workflow_dispatch

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/frontend
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    if: contains(fromJson('["main", "staging", "dev"]'), github.ref_name)
    name: Build and push from ${{ github.ref_name }}/${{ github.sha }}
    environment: 'local'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}-local,${{ env.IMAGE_NAME }}:${{github.ref_name}}-local
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VITE_API_URL=${{ vars.VITE_API_URL }}
            VITE_ENVIRONMENT_NAME=${{ vars.VITE_ENVIRONMENT_NAME }}
            VITE_MODEL_NAME=${{ vars.VITE_MODEL_NAME }}
            VITE_MODEL_MODE=${{ vars.VITE_MODEL_MODE }}
            VITE_MODEL_TEMPERATURE=${{ vars.VITE_MODEL_TEMPERATURE }}
            VITE_MATOMO_URL=${{ vars.VITE_MATOMO_URL }}
